eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hmilyos/springcloud-config-repo.git
          username:
          password:
          basedir: G:/test/java/springCloud/config/basedir

