eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hmilyos/springcloud-config-repo.git
          username:
          password:
          basedir: G:/test/java/springCloud/config/basedir
  rabbitmq:
    host: 192.168.0.7
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

